### ISSUE TITLE
Making slides with rmd

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/MCL-DSCI-511-programming-in-python#12]

**Comment by hfboyce** [comment]
Currently working on this.

**Comment by hfboyce** [comment]
There is a document named [slide-construction.Rmd](https://github.com/UBC-MDS/MCL-DSCI-511-programming-in-python/blob/master/slide-construction.Rmd) in the root of this repo which if knited, will give a similar but not not quite version of what we need our md document to look like for slides. 
There are 3 things that need to be changed to the output: 

1. `---` these slide indicators in the `.rmd` file convert to `-----` in the `.md` file which is a problem for creating slides since the latter is not regonized as a "new slide".

2. The code 
```
---
type: slides
---
```
at the top of the `.rmd` file gets lost. We need to have this in the knited `.md` file.

3. The output of the code chunks need to be in the format (take away the `.` at the beginning) 

> .```out
>
>.```

without this, the code will not appear as outputted code. 

I have looked into pandoc and `pandoc_args` and I am struggling to figure out how to make this customization. 
Here are some ressources that might help: 
- https://rmarkdown.rstudio.com/docs/reference/md_document.html
- https://pandoc.org/MANUAL.html
- https://bookdown.org/yihui/rmarkdown/markdown-document.html
- https://yihui.org/knitr/options/
- https://rmarkdown.rstudio.com/authoring_pandoc_markdown.html%23raw-tex

At this point I need to more on to something else because I am at a stand-still.

**Comment by ttimbers** [comment]
For the output code chunk there is `attr.output` that can be set as a code chunk option...

**Comment by ttimbers** [comment]
OK, I have decided to do things the not proper, but fast way using regex, how does this look @hfboyce: https://raw.githubusercontent.com/UBC-MDS/MCL-DSCI-511-programming-in-python/master/slide-construction-FIXED.md

**Comment by hfboyce** [comment]
It looks amazing!

**Comment by ttimbers** [comment]
Done in 088e7d04
