### ISSUE TITLE
Do we need to wrap functions in print statements

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/MCL-DSCI-511-programming-in-python#5]
Nested function composition (e.g., `print(len(df))`) can be complicated for beginners. Do we need these in module 1? Won't the code in the slides just work with `len(df)`, for example? I know it's important for them to learn that without print, only the last object will be output into a code cell, but can we delay that until later in module 1, or even a later module?

**Comment by hfboyce** [comment]
Removed!
