### ISSUE TITLE
"Your first code" is missing the name of the file

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/MCL-DSCI-511-programming-in-python#6]
The learner is not told what the name of the file we need to load is, and so they will not be able to solve this question. Please add that to the instructions.

**Comment by ttimbers** [comment]
Also, the follow-on question essentially gives the answer to this one. Can we separate these visually somehow? Also, can the objects not persist between code blocks (i.e., if we already loaded a data set, can we not call it and work on it in a following code chunk)?

**Comment by hfboyce** [comment]
> The learner is not told what the name of the file we need to load is, and so they will not be able to solve this question. Please add that to the instructions.
Done!

Also, the follow-on question essentially gives the answer to this one. Can we separate these visually somehow?
I Split them up! 

> Also, can the objects not persist between code blocks (i.e., if we already loaded a data set, can we not call it and work on it in a following code chunk)?

We can but it must be so for the whole course as documented [here](https://github.com/ines/course-starter-python/issues/13)

I am testing it out and pushing the changes, not sure if it will work though.

**Comment by ttimbers** [comment]
Send the Q to Ines!

**Comment by hfboyce** [comment]
Closing this, Opened this as a separate issue in #13
